### ISSUE TITLE
Panning and zooming needs improvement

### ISSUE THREAD

**Issue by tomayac** [tomayac/SVGcode#16]
Better on desktop, but still not feels 100% natural. It's worse on mobile.

**Comment by dwelle** [comment]
The biggest problem I see is that panning doesn't account for zoom. On high zoom, slight panning moves the canvas too much. When zoomed out, panning barely moves the canvas.

Another bug: once you pan, you can zoom in/out beyond the limit. Repro: 1) zoom out to 0.1 2) pan canvas a bit 3) you are allowed to zoom out again 4) repeat ad infinitum.

**Comment by Fuzzyma** [comment]
Maybe it helps to see how https://github.com/svgdotjs/svg.panzoom.js does it. I am the Maintainer and afaik it works pretty good

**Comment by tomayac** [comment]
I have now moved to `pinch-zoom`, which introduced a drifting bug on pinch-zooming, tracked in #46. It's definitely still better than what we had before. Hoping for an eventual fix here.
