### ISSUE TITLE
Feature-detect SVG copy feature

### ISSUE THREAD

**Issue by argyleink** [tomayac/SVGcode#18]
puts this into my clipboard:

"Notes
Responsive SVG/container query
asset delivery strategy
color sync
Parallax (scroll timeline)
Animation
hosting
subdomain
web.dev
post explainer
link out on homepage
social share
meta
branding / images
tweets from Chromium accounts
instagram cross postss
cron job
runs daily to build site and reveal new item

Questions
Scroll focused or flashlike?
Types of content behind advent days?
Mobile or desktop first?

Action items
UI Architecture
accessible
print
Github Repo
Advent item component
visible or not
interacted with or not
Responsive advent grid
image pipeline
Stateful for users?
RSS / Push Notifications
Early and often audits from perf pros
Analytics
will effect ariane
"

**Comment by dwelle** [comment]
Is this fixed? I'm getting:

```
DOMException: Type image/svg+xml not supported on write.
```

I recall we were facing the [same issue in Excalidraw](https://github.com/excalidraw/excalidraw/issues/386#issuecomment-581444340), so it seems the clipboard API still doesn't support it?

**Comment by tomayac** [comment]
It's supported now :-) https://async-clipboard-tests.glitch.me/ (ignore the "Paste HTML" button)

**Comment by dwelle** [comment]
I'm getting (Stable + Canary):

![image](https://user-images.githubusercontent.com/5153846/143469936-629f1b05-1baf-485f-ad00-9fbee57bb2e2.png)

even if I enable `chrome://flags/#clipboard-custom-formats` (though I'm sure you didn't mean one needs that enabled anyway)

**Comment by tomayac** [comment]
It should be behind the `#experimental-web-platform-features` flag according to [ChromeStatus](https://chromestatus.com/feature/5125790490427392). This is the [tracking bug](https://crbug.com/1110511). So it works, but is not exposed to the general Chrome public.

**Comment by dwelle** [comment]
Ok, with that flag it works. Shouldn't that requirement be communicated? Right now clicking the button on https://svgco.de says the copy operation succeeded while not true :p

**Comment by tomayac** [comment]
That’s right. Re-opening with new title. Thanks!

**Comment by notiv-nt** [comment]
Why not just remove `image/svg+xml` ?

```
// prevent DOMException: Document is not focused
setTimeout(() => {
  const textBlob = new Blob(['it works'], { type: 'text/plain' });

  navigator.clipboard.write([
    new ClipboardItem({
      [textBlob.type]: textBlob,
    }),
  ]);
  
  console.log('copied')
}, 2000);
```

**Comment by tomayac** [comment]
Yes, falling back to copying the source code instead of the actual image is what I will probably go with. That's also the approach that I [suggest in a related blog post](https://blog.tomayac.com/2020/03/20/multi-mime-type-copying-with-the-async-clipboard-api/#multi-mime-type-copying).

**Comment by notiv-nt** [comment]
@tomayac still doesn't work btw: `NotAllowedError Type image/svg+xml not supported on write.`

**Comment by tomayac** [comment]
I just verified the fix in BrowserStack on a completely vanilla Chrome 96 with no flags at all set. On the right you can see SVGcode with the fallback chain visible in the DevTools console where it tries to copy SVG as an image, fails, and then falls back to plain text (the SVG source code if you will) that I then paste into SVGOMG, which you can see on the left.

<img width="1792" alt="Screen Shot 2021-12-01 at 12 08 37" src="https://user-images.githubusercontent.com/145676/144224177-83acf179-b1ff-423c-8205-980c0948d3d5.png">

What browser version does this happen on for you? Can you try again in a fresh browser profile without cache? Thanks!

**Comment by notiv-nt** [comment]
@tomayac Yes, it works. I just didn't expect to wait for 7s to optimize
Chrome v96, mac 16, monterey

**Comment by tomayac** [comment]
That's great, thanks for confirming! Yes, Potrace has the tendency to produce a lot of paths. To fight this, you can tweak the posterization settings, despeckle more aggressively, or in the expert options require a longer minimum path length to remove short paths that mostly add noise.
