### ISSUE TITLE
Add to home screen on mobile triggers widget addition

### ISSUE THREAD

**Issue by rowan-m** [tomayac/SVGcode#21]
Chrome 96.0.4664.45 on Android 12, Pixel 5. Add to home screen triggers home screen widget addition as opposed to install. Appears to work fine on ChromeOS desktop though.
![Add to home screen showing the widget addition dialog](https://user-images.githubusercontent.com/108052/142173690-1cd59c21-ad26-4694-a882-cd26de1bc0d5.jpg)

**Comment by tomayac** [comment]
Thanks, @rowan-m! I need to update our docs as well, they are missing this, too. https://web.dev/codelab-make-installable/ On it now!
