### ISSUE TITLE
Change link in repo description?

### ISSUE THREAD

**Issue by Malvoz** [tomayac/SVGcode#22]
https://svgco.de/dist/ should probably be https://svgco.de/ in the About description 😋

**Comment by Malvoz** [comment]
Never mind, probably had a cached version since of yesterday when that link didn't work...

**Comment by Malvoz** [comment]
Actually, I'm getting inconsistent behavior:

https://user-images.githubusercontent.com/26493779/142420415-96279376-9b3e-4e20-b58b-4964d743febd.mp4

(this only seems to happen on /dist/)

**Comment by Malvoz** [comment]
I see you did change the link now. Closing again, sorry for all the fuss.

**Comment by tomayac** [comment]
No worries. It’s a bit of a stealth launch. There will be a video and an article to accompany the official release.
