### ISSUE TITLE
Install button doesn't disappear after install

### ISSUE THREAD

**Issue by steren** [tomayac/SVGcode#23]
I installed the PWA on windows, but even after Install. I still see an "install" button in the top bar. I'd expect it to disappear once I have installed

**Comment by tomayac** [comment]
I changed the visibility logic a minute before the video went live and must have broken something. I’ll have a look after the weekend. Thanks for reporting this issue!

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/SVGcode/commit/67ce8b64d1b1c833e2688eb4be90018151dc31cf.
