### ISSUE TITLE
Does the site store configured settings?

### ISSUE THREAD

**Issue by LukePrior** [tomayac/SVGcode#25]
Hi,

I have been using the site for a little bit and it has been extremely useful. I have configured the settings specifically for the specific style of images I need to convert and this works perfectly however all values are reset upon closure of the site. I was wondering if something is going wrong here or if this is just not currently a feature?

Thanks.

**Comment by tomayac** [comment]
Thanks for reporting this feature request. It’s simply currently not implemented yet. I’ll see what I can do. It should probably also be configurable whether settings are stored and there currently also is no preferences section yet.
