### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'resetAll')

### ISSUE THREAD

**Issue by kurtextrem** [tomayac/SVGcode#31]
I tested Edge Stable & Chrome Dev, and I can't get the website to work. It looks like this: 
![image](https://user-images.githubusercontent.com/502146/142760830-ce2b035d-d1fd-4c54-998e-19891895d27a.png)

localStorage language entry is: `"{"language":"de","locale":null}"`

The error is triggered here: https://github.com/tomayac/SVGcode/blob/f6f00b1b493cb80d84ce336a20d10a6ea0a25e9e/src/js/i18n.js#L72

right after this is called:
https://github.com/tomayac/SVGcode/blob/f6f00b1b493cb80d84ce336a20d10a6ea0a25e9e/src/js/i18n.js#L55-L62

I'm not sure what the issue is, because if I call the loader fn manually (with `'../i18n/de.js'`) my promise resolves correctly to a `Module`. But since `de.js` is empty... reading `.default` on it doesn't work?

**Comment by kurtextrem** [comment]
Two options: We wrap the line in a try ... catch or we make sure there are no i18n files that are empty in the future. What do you think?

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/SVGcode/commit/3d2409ece8dcf1a914ec10d2e0d51e171ffcc10f#diff-84f6078d84f6fb4989bcfecc9912f18cc5d83b6924d395db9ca7c74aecc14fcd.
