### ISSUE TITLE
Buttons in top menu partially hidden when menu height is becoming small.

### ISSUE THREAD

**Issue by georapbox** [tomayac/SVGcode#35]
## Description 

The height of the top menu element changes depending on the viewport dimensions and aspect ratio. This results in the buttons located in the menu to be partially hidden (see attached screenshot).

<img width="1361" alt="Screenshot 2021-11-23 at 10 07 13 AM" src="https://user-images.githubusercontent.com/6596039/142989042-a29832c9-2b25-4c51-8587-bf94d03cc633.png">

## Steps to reproduce

One way to reproduce, is to resize the viewport vertically while leaving the viewport's width in full screen. Another case that this is easily reproducible, is when viewing in ultra wide screens.

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/SVGcode/pull/36.
