### ISSUE TITLE
Console error and loader keeps spinning

### ISSUE THREAD

**Issue by maeligg** [tomayac/SVGcode#47]
Hi,

When I upload a PNG file, the loader keeps spinning and I see the following error in the console :
`Uncaught ReferenceError: CanvasFilter is not defined at getFilter...`
Tested in Chrome latest on OSX.

**Comment by tomayac** [comment]
I just rolled back a commit that may have caused the endless spinner. Could you reload the app and try again, please? If it doesn't work, could you send me the output of when you put `chrome://version/` in the URL bar, please?

**Comment by maeligg** [comment]
Thanks ! I can confirm it's working again.

**Comment by tomayac** [comment]
Perfect! Sorry for the short interruption, and thanks for letting me know. Closing the issue then.
