### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by notiv-nt** [tomayac/SVGcode#48]
Would be awesome to have this feature

**Comment by tomayac** [comment]
For the time being, you can feed the result of [SVGcode](https://svgco.de/) into an online editor like [SVG-edit](https://svgedit.netlify.app/editor/index.html). I may be able to realize this feature relatively cheaply in my app by adding a CSS rotation to the input image.

**Comment by tomayac** [comment]
![localhost_3000_](https://user-images.githubusercontent.com/145676/151626182-3273488e-3a5a-4d83-9f83-ff8ba397d8b6.png)
