### ISSUE TITLE
I got the Arabic version when open it on Safari both iPhone and MacOS

### ISSUE THREAD

**Issue by tyohan** [tomayac/SVGcode#76]
Nice work @tomayac, happy to see the Bahasa Indonesia also included in this project. I tried opening the svgco.de with my iPhone and somehow I got the Arabic version by default. As your request, I open it on my Macbook Air with Safari and see an error log in the console like this:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/106703/154231284-a7d3bf80-6dcc-4f3c-aba9-805814d294e6.png">

It seems the `en-CA` locale is not supported on my side and fallback to Arabic. 

I hope this helps.

**Comment by tomayac** [comment]
Oh, yes. Definitely the locale (I support en-US and en-GB). Thanks for the Issue, I hope to have a fix soon.
