### ISSUE TITLE
Add ability to change background color, to evaluate results

### ISSUE THREAD

**Issue by Stokestack** [tomayac/SVGcode#83]
If you're tracing a dark image, it can hard to evaluate results in the preview pane. It would help to be able to set the background color, or at least toggle between light & dark.

Currently I'm not sure what the results window is showing, because it shows a highly speckled and indistinct image despite the output of the tool being a nice, crisp SVG (I was using a black-&-white mostly-text image).

This tool works well, nice job.

**Comment by tomayac** [comment]
I have a dark mode toggle ready to go, but am waiting for https://github.com/vitejs/vite/issues/6748 to be fixed before I can use it. Thanks for the kind words!

**Comment by tomayac** [comment]
@Stokestack The dark mode toggle is now enabled and ready to go. Find it in the lower left corner of the side bar.

**Comment by Stokestack** [comment]
Great, I'll check it out! Thanks!
