### ISSUE TITLE
How to build on ARM64 M1 chip Macbook Pro

### ISSUE THREAD

**Issue by blacklein** [tomayac/SVGcode#84]
How to build on ARM64 M1 chip Macbook Pro?

**Comment by tomayac** [comment]
Could you post the error message you’re getting? Else I don’t know what problem you run into. Thanks!

**Comment by blacklein** [comment]
```
❯ npm install
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

> SVGcode@0.0.1 prepare
> npm run icons && npm run build


> SVGcode@0.0.1 icons
> node ./scripts/icons.mjs

file:///Users/usrname/Downloads/SVGcode/node_modules/node-fetch/src/index.js:108
			reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
			       ^

FetchError: request to https://raw.githubusercontent.com/google/material-design-icons/master/src/image/tune/materialicons/24px.svg failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (file:///Users/usrname/Downloads/SVGcode/node_modules/node-fetch/src/index.js:108:11)
    at ClientRequest.emit (node:events:537:28)
    at TLSSocket.socketErrorListener (node:_http_client:465:9)
    at TLSSocket.emit (node:events:537:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  erroredSysCall: 'read'
}

Node.js v18.4.0
npm ERR! code 1
npm ERR! path /Users/usrname/Downloads/SVGcode
npm ERR! command failed
npm ERR! command sh -c /var/folders/5c/68bnmldx059fyp56djl1h6bh0000gn/T/prepare65697438253.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/usrname/.npm/_logs/2022-07-04T04_03_53_678Z-debug-0.log
```

**Comment by tomayac** [comment]
It looks like you're on an outdated version that had the SVGs referenced from elsewhere. Can you run `git pull` and then `npm ci` to try again?

**Comment by blacklein** [comment]
`npm ci` works
```
added 746 packages in 12s

101 packages are looking for funding
  run `npm fund` for details
```
and what's next step? tried `npm run build` but no executable generated

**Comment by tomayac** [comment]
You can see all available commands by running `npm run`. You can start developing by running `npm start`.

**Comment by blacklein** [comment]
npm start works properly, but wonder how to build a desktop app showed up in readme.md like below:
<img width="1414" alt="desktop" src="https://user-images.githubusercontent.com/69177971/177088737-768f93fc-c0c7-4173-a50c-ed701e87316d.png">

**Comment by tomayac** [comment]
Oh, I see `:-)`… This is actually not a desktop app, but a Progressive Web App, but installed and with the [Window Controls Overlay](https://web.dev/window-controls-overlay/) feature activated. Watch the video at https://web.dev/svgcode/#window-controls-overlay to see how to enable this.

**Comment by blacklein** [comment]
ok, very helpful, thanks a lot! I mistakenly thought this project was an application packaged with electron.

**Comment by tomayac** [comment]
Perfect then, glad the misunderstanding was resolved. The difference to Electron.js apps is becoming smaller and smaller indeed.
