### ISSUE TITLE
Crash when opened with cookies blocked

### ISSUE THREAD

**Issue by JakubekWeg** [tomayac/SVGcode#86]
Hey
I block cookies by default. Unfortunately your website doesn’t handle that nicely despite it not needing (IMO) cookies to operate.
I'm getting this error, because blocking cookies also blocks localStorage.
```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
```
Please add fallback to js provided localStorage, because it makes the app unusable.

**Comment by tomayac** [comment]
I think this is fixed via 

- https://github.com/tomayac/SVGcode/commit/b9d2c59bc579c103b8ac154432d65eec9688e853
- https://github.com/tomayac/SVGcode/commit/036ddd27cbcc7923b0f8da7072a34a0e3de764b1

Please report any additional errors you encounter here. Thanks for reporting!

**Comment by tomayac** [comment]
This turned out to be interesting blogging material… https://blog.tomayac.com/2022/08/30/things-not-available-when-someone-blocks-all-cookies/. Thanks for reporting this Issue again.
