### ISSUE TITLE
Convert All Contents of a Folder

### ISSUE THREAD

**Issue by mpurl** [tomayac/SVGcode#87]
Can we have an option to convert all images in a folder in one step?

**Comment by tomayac** [comment]
Hmmm, interesting. This should be possible, but will create some interesting UI challenges. Which of all these images would you show to the user for example for them to see the effect of the sliders?

**Comment by mpurl** [comment]
> Hmmm, interesting. This should be possible, but will create some interesting UI challenges. Which of all these images would you show to the user for example for them to see the effect of the sliders?

I think there are multiple approaches with different difficulties.
Some ideas could be:

- creating a php or python script that can be called from the terminal with parameters such as folder path and slider options (one setting for all images)
- just adding a button "convert folder items" and use the current settings of all images
- show first (or random image) of the folder and use these settings for all other

I would say that using the same setting for all images would be fine for 90% of all use-cases. If someone is not satisfied with a result, he/she can still convert these images with individual settings manually.
Another (maybe over-engineered) solution could be using two chevrons (< >) to switch between the images, but I think the effort of implementation don't match the benefits.

**Comment by tomayac** [comment]
Just to be sure: this tool is based on `potrace`, which already can be used to batch-convert images from the command line. See [this post](https://unix.stackexchange.com/a/110835) for details. Does this help?

**Comment by mpurl** [comment]
Yeah, but `potrace` only allows bitmap input and no png files

**Comment by tomayac** [comment]
ImageMagick to the rescue:

`convert input.jpg output.ppm`

**Comment by lolo9538** [comment]
Thank you @tomayac it's exactly what I needed. Combine with your great tool I was able to finetune the ideal parameters for potrace.

**Comment by tomayac** [comment]
@lolo9538 Brilliant, glad this workflow, well, worked for you!
