### ISSUE TITLE
Firefox with `ClipboardItem` enabled copies `[object Promise]`

### ISSUE THREAD

**Issue by silverwind** [tomayac/SVGcode#90]
To reproduce:

- Open latest Firefox
- Set `dom.events.asyncClipboard.clipboardItem` in `about:config`
- Open the application, click `Copy SVG`
- It copies the string `[object Promise]`

I'm not sure where this goes wrong, but I suspect it has something to do with the user agent sniffing. I'm using this same API in [this module](https://github.com/silverwind/clippie), so I think it is operational and the bug is from this app code, not from Firefox.

**Comment by tomayac** [comment]
This is the relevant code: https://github.com/tomayac/SVGcode/blob/80bc0bdc1e2a93ec3b022ebffbc0038a1714f8a1/src/js/clipboard.js#L65. What operating system does this happen on?

**Comment by silverwind** [comment]
MacOS, `window.ClipboardItem` does exist with the `about:config` preference enabled.

**Comment by tomayac** [comment]
Thanks for the report. I will take a look soon.

**Comment by silverwind** [comment]
I think the likely fix will be to remove the `Promise` wrapping. I tested the API with non-promise and Safari copied it fine. The fact that it works with Promise in Safari while not in Firefox is likely an implementation difference between the two.

**Comment by tomayac** [comment]
Fixed via https://github.com/tomayac/SVGcode/commit/4a2234480c6b2105577310e90b7da7d0ae80c127. Thanks for reporting!

**Comment by silverwind** [comment]
Thanks, confirmed working!
