### ISSUE TITLE
Consider using ClipboardItem.supports to detect if copying SVGs to the clipboard is supported

### ISSUE THREAD

**Issue by yisibl** [tomayac/SVGcode#93]
I see that currently using userAgent for detection, it would be more ergonomic to use `ClipboardItem.supports`. Currently, only Chrome supports this API.

https://github.com/tomayac/SVGcode/blob/8371a65aef90b333980baabc425ff02aee32cac0/src/js/clipboard.js#L72-L86

It can be adjusted to:

```js
if (ClipboardItem.supports('image/svg+xml')) {
  // do something
}
```

My Microsoft partners @snianu and I [recently fixed](https://chromium-review.googlesource.com/c/chromium/src/+/5278640) this API's support for `image/svg+xml`, which has been merged into [Chrome 123.0.6298.0](https://chromiumdash.appspot.com/commit/8fdf59f128da4dcf707156342dc1a3301b4b74fa).

However, I'm not sure if SVGcode can abandon older versions of Chrome.

**Comment by tomayac** [comment]
Thanks for the suggestion. I think the way I use it now as a progressive enhancement should work:

```js
if (
  ('supports' in ClipboardItem &&
    ClipboardItem.supports('image/svg+xml')) ||
  !IS_SAFARI
) { /* … */ }
```

Once browser support is better, the UA sniffing part can go, too.
